embeddings:
  per_signal_overrides:
    input:
      magnetics-flux_loop_flux:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_flux_loop_flux

      magnetics-b_field_pol_probe_ccbv_field:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_b_field_pol_probe_ccbv_field

      magnetics-b_field_pol_probe_obr_field:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_b_field_pol_probe_obr_field

      magnetics-b_field_tor_probe_saddle_voltage:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_b_field_tor_probe_saddle_voltage

      magnetics-b_field_pol_probe_obv_field:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_b_field_pol_probe_obv_field

      pf_active-coil_current:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_coil_current

      pf_active-solenoid_current:
        encoder_name: vae
        encoder_kwargs:
          model_dir: linear_vae_config_solenoid_current

      summary-ip:
        encoder_name: vae
        encoder_kwargs:
          model_dir: linear_vae_config_summary_ip

    output:
      equilibrium-psi:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv2d_vae_config_equilibrium_psi
