embeddings:
  per_signal_overrides:
    input:
      magnetics-flux_loop_flux:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_flux_loop_flux

      magnetics-b_field_pol_probe_ccbv_field:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_b_field_pol_probe_ccbv_field

      magnetics-b_field_pol_probe_obr_field:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_b_field_pol_probe_obr_field

      magnetics-b_field_tor_probe_saddle_voltage:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_b_field_tor_probe_saddle_voltage

      magnetics-b_field_pol_probe_obv_field:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_b_field_pol_probe_obv_field

      pf_active-coil_current:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_coil_current

      pf_active-solenoid_current:
        encoder_name: vae
        encoder_kwargs:
          model_dir: linear_vae_config_solenoid_current

      summary-ip:
        encoder_name: vae
        encoder_kwargs:
          model_dir: linear_vae_config_summary_ip

    output:
      equilibrium-elongation:
        encoder_name: identity

      equilibrium-elongation_axis:
        encoder_name: identity

      equilibrium-triangularity_upper:
        encoder_name: identity

      equilibrium-triangularity_lower:
        encoder_name: identity

      equilibrium-x_point_r:
        encoder_name: identity

      equilibrium-x_point_z:
        encoder_name: identity

      equilibrium-minor_radius:
        encoder_name: identity

      equilibrium-magnetic_axis_r:
        encoder_name: identity

      equilibrium-magnetic_axis_z:
        encoder_name: identity

      equilibrium-q95:
        encoder_name: identity

      equilibrium-beta_tor:
        encoder_name: identity

      equilibrium-beta_pol:
        encoder_name: identity

      equilibrium-beta_normal:
        encoder_name: identity

      equilibrium-bvac_rmag:
        encoder_name: identity

      equilibrium-bphi_rmag:
        encoder_name: identity
